### ISSUE TITLE
Errorring package.json scripts for 'build', 'check', 'test', 'coverage'

### ISSUE THREAD

**Issue by loklaan** [Effect-TS/examples#44]
### What version of Effect is running?

latest

#### `Basic` template

1. Install the basic template, `pnpm create effect-app@latest` selecting `Basic` with all options `on`
2. Install deps with `pnpm install`
3. Run the commands listed
  - `pnpm run build`
  - `pnpm run check`
  - `pnpm run test`
  - `pnpm run coverage`
  - `pnpm run codegen`

#### `CLI Application` template

1. Install the cli template, `pnpm create effect-app@latest` selecting `CLI Application` with all options `on`
2. Install deps with `pnpm install`
3. Run the commands listed
  - `pnpm run build`
  - `pnpm run check`
  - etc

#### `Monorepo` template

1. Install the cli template, `pnpm create effect-app@latest` selecting `Monorepo` with all options `on`
2. Install deps with `pnpm install`
3. Run the commands listed
  - `pnpm run build`
  - etc

### What is the expected behavior?

The expected behaviour should _probably_ be passing exit codes etc

#### `Basic` template

<details>
<summary>build</summary>

<img width="1422" alt="image" src="https://github.com/user-attachments/assets/c6af14c9-fc3e-47cc-bf0b-5838c6574632">

</details>

<details>
<summary>check</summary>

<img width="931" alt="image" src="https://github.com/user-attachments/assets/00cc0291-0c90-4113-a19d-f76d0a5ced50">

</details>

<details>
<summary>test</summary>

<img width="1424" alt="Screenshot 2024-09-15 at 4 08 00 pm" src="https://github.com/user-attachments/assets/a543c0a0-c7e1-42b0-9b03-49d943e2aacb">

</details>

<details>
<summary>coverage</summary>

<img width="1425" alt="Screenshot 2024-09-15 at 4 08 30 pm" src="https://github.com/user-attachments/assets/3880028b-d601-458f-8cc9-0c2781f8c52b">

</details>

<details>
<summary>codgen</summary>

<img width="1401" alt="image" src="https://github.com/user-attachments/assets/3c31812d-d3f6-4355-8bf8-87275bb3154d">

</details>

#### `CLI Application` template

<details>
<summary>build</summary>

<img width="705" alt="Screenshot 2024-09-15 at 4 15 37 pm" src="https://github.com/user-attachments/assets/ff0e6b6e-db86-4535-bfb4-3d38778a4b81">

</details>

<details>
<summary>check</summary>

<img width="1420" alt="Screenshot 2024-09-15 at 4 16 51 pm" src="https://github.com/user-attachments/assets/fe86950b-6784-4874-ba6a-7eac67393721">

</details>

#### `Monorepo` template

I stopped taking screenshots here, just rerun commands mentioned above for this template and they'll fail where they fail.

### Additional information

I didn't get to trying to run the package.json scripts for the `Http-sever` example, it's worth running those to see if they suffer from similar misconfigs.

Thanks for all the hard work! This'll be out-of-the-gate awesome when these bugs are squashed! Right now, generated projects will run fine _after_ fixing the various obvious issues. 👍

**Comment by IMax153** [comment]
@loklaan - thank you very much for the detailed report! 🙏 

We are working on adding some CI jobs that will help us detect when there are errors with the templates / examples, but for now I've created a PR to hopefully resolve these issues!
